/**
 * Generates an OpenAPI 3.0 specification from extracted edge function metadata.
 */
import type { EdgeFunctionItem, EdgeFunctionField } from "./extractor.js";

interface OpenApiOptions {
  apiUrl: string;
  baseUrl: string;
}

interface OpenApiSpec {
  openapi: string;
  info: { title: string; description: string; version: string };
  servers: { url: string; description: string }[];
  paths: Record<string, Record<string, unknown>>;
  components: { securitySchemes: Record<string, unknown> };
}

/**
 * Generate an OpenAPI 3.0 spec from edge function items.
 */
export function generateEdgeFunctionOpenApi(
  items: EdgeFunctionItem[],
  opts: OpenApiOptions
): OpenApiSpec {
  const paths: Record<string, Record<string, unknown>> = {};

  for (const fn of items) {
    const pathKey = `${opts.baseUrl}/${fn.name}`;
    const methods = fn.methods.filter((m) => m !== "OPTIONS");

    for (const method of methods) {
      const methodLower = method.toLowerCase();

      const operation: Record<string, unknown> = {
        summary: fn.description || fn.name,
        operationId: `${fn.name}_${methodLower}`,
        tags: ["Edge Functions"],
        responses: buildResponses(fn),
      };

      // Security
      if (fn.auth_type === "jwt") {
        operation.security = [{ bearerAuth: [] }, { apiKey: [] }];
      } else if (fn.auth_type === "service_role") {
        operation.security = [{ bearerAuth: [] }, { apiKey: [] }];
      } else {
        operation.security = [{ apiKey: [] }];
      }

      // Request body for non-GET methods
      if (methodLower !== "get" && fn.request_fields.length > 0) {
        operation.requestBody = {
          required: true,
          content: {
            "application/json": {
              schema: buildRequestSchema(fn.request_fields),
              example: buildExample(fn.request_fields),
            },
          },
        };
      }

      // External API dependencies as x-extension
      if (fn.external_apis.length > 0) {
        operation["x-external-apis"] = fn.external_apis;
      }

      // DB tables as x-extension
      if (fn.db_tables.length > 0) {
        operation["x-database-tables"] = fn.db_tables;
      }

      // Env vars as x-extension
      if (fn.env_vars.length > 0) {
        operation["x-environment-variables"] = fn.env_vars;
      }

      if (!paths[pathKey]) {
        paths[pathKey] = {};
      }
      paths[pathKey][methodLower] = operation;

      // Add OPTIONS for CORS
      if (fn.cors) {
        paths[pathKey]["options"] = {
          summary: "CORS preflight",
          operationId: `${fn.name}_options`,
          tags: ["Edge Functions"],
          responses: {
            "204": {
              description: "CORS preflight response",
              headers: {
                "Access-Control-Allow-Origin": {
                  schema: { type: "string", example: "*" },
                },
                "Access-Control-Allow-Headers": {
                  schema: { type: "string" },
                },
              },
            },
          },
        };
      }
    }
  }

  return {
    openapi: "3.0.3",
    info: {
      title: "Edge Functions API",
      description:
        "Auto-generated OpenAPI specification for Supabase Edge Functions. Generated by @sbtools/plugin-deno-functions.",
      version: "1.0.0",
    },
    servers: [
      {
        url: opts.apiUrl,
        description: "Local Supabase instance",
      },
    ],
    paths,
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
          description: "Supabase JWT token (anon or service_role)",
        },
        apiKey: {
          type: "apiKey",
          in: "header",
          name: "apikey",
          description: "Supabase anon or service_role API key",
        },
      },
    },
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function fieldTypeToJsonSchema(field: EdgeFunctionField): Record<string, unknown> {
  const t = (field.type || "").toLowerCase();
  if (t.includes("uuid")) return { type: "string", format: "uuid" };
  if (t.includes("boolean") || t === "boolean") return { type: "boolean" };
  if (t.includes("number") || t === "number") return { type: "number" };
  if (t.includes("object")) return { type: "object" };
  if (t.includes("array")) return { type: "array", items: { type: "string" } };
  return { type: "string" };
}

function buildRequestSchema(
  fields: EdgeFunctionField[]
): Record<string, unknown> {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const f of fields) {
    properties[f.name] = {
      ...fieldTypeToJsonSchema(f),
      description: f.name,
    };
    if (f.required !== false) {
      required.push(f.name);
    }
  }

  return {
    type: "object",
    properties,
    ...(required.length > 0 ? { required } : {}),
  };
}

function buildExample(fields: EdgeFunctionField[]): Record<string, unknown> {
  const example: Record<string, unknown> = {};
  for (const f of fields) {
    const t = (f.type || "").toLowerCase();
    if (t.includes("uuid")) {
      example[f.name] = "00000000-0000-0000-0000-000000000000";
    } else if (t.includes("boolean")) {
      example[f.name] = true;
    } else if (t.includes("number")) {
      example[f.name] = 0;
    } else {
      example[f.name] = "...";
    }
  }
  return example;
}

function buildResponses(fn: EdgeFunctionItem): Record<string, unknown> {
  const responses: Record<string, unknown> = {
    "200": {
      description: "Successful response",
      content: {
        "application/json": {
          schema: fn.response_fields.length > 0
            ? buildResponseSchema(fn.response_fields)
            : { type: "object" },
        },
      },
    },
    "400": {
      description: "Bad request",
      content: {
        "application/json": {
          schema: {
            type: "object",
            properties: { error: { type: "string" } },
          },
        },
      },
    },
    "500": {
      description: "Internal server error",
      content: {
        "application/json": {
          schema: {
            type: "object",
            properties: {
              error: { type: "string" },
              details: { type: "string" },
            },
          },
        },
      },
    },
  };

  return responses;
}

function buildResponseSchema(
  fields: EdgeFunctionField[]
): Record<string, unknown> {
  const properties: Record<string, unknown> = {};

  for (const f of fields) {
    properties[f.name] = {
      ...fieldTypeToJsonSchema(f),
    };
  }

  return {
    type: "object",
    properties,
  };
}
