/**
 * Shared utilities for sbt onboarding test scripts.
 *
 * Provides:
 *  - runCli()   – invoke the local CLI source (no build/publish needed)
 *  - clean()    – strip generated files from the target dir between tests
 *  - assert()   – throw with a clear message on failure
 *  - log helpers
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// ---------------------------------------------------------------------------
// Repo-root paths (resolved relative to this file)
// ---------------------------------------------------------------------------

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/** Absolute path to the monorepo root. */
export const REPO_ROOT = path.resolve(__dirname, "..");

/** tsx binary — .cmd on Windows, plain on Unix. */
export const TSX =
  process.platform === "win32"
    ? path.join(REPO_ROOT, "node_modules", ".bin", "tsx.cmd")
    : path.join(REPO_ROOT, "node_modules", ".bin", "tsx");

/** The local CLI entry point (TypeScript source, no build needed). */
export const CLI = path.join(REPO_ROOT, "packages", "core", "src", "cli.ts");

// ---------------------------------------------------------------------------
// CLI runner
// ---------------------------------------------------------------------------

export interface RunResult {
  stdout: string;
  stderr: string;
  combined: string;
  exitCode: number;
}

/**
 * Run the local sbt CLI with the given args.
 * The target directory is used as the working directory so the CLI reads
 * config from there (mimicking how a real user would run sbt).
 *
 * Does NOT throw on non-zero exit — returns the exit code instead so tests
 * can assert on expected failures.
 */
export function runCli(args: string[], cwd: string): RunResult {
  // shell:true is required on Windows so that .cmd files can be executed
  const result = spawnSync(TSX, [CLI, ...args], {
    cwd,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    shell: true,
  });
  const stdout = result.stdout ?? "";
  const stderr = result.stderr ?? "";
  return {
    stdout,
    stderr,
    combined: stdout + stderr,
    exitCode: result.status ?? 1,
  };
}

// ---------------------------------------------------------------------------
// Assertions
// ---------------------------------------------------------------------------

export function assert(condition: boolean, message: string): void {
  if (!condition) throw new Error(`ASSERT FAILED: ${message}`);
}

export function assertContains(text: string, substring: string): void {
  if (!text.includes(substring)) {
    throw new Error(
      `ASSERT FAILED: expected output to contain:\n  "${substring}"\ngot:\n${text}`,
    );
  }
}

export function assertNotContains(text: string, substring: string): void {
  if (text.includes(substring)) {
    throw new Error(
      `ASSERT FAILED: expected output NOT to contain:\n  "${substring}"\ngot:\n${text}`,
    );
  }
}

export function assertExitCode(result: RunResult, expected: number): void {
  if (result.exitCode !== expected) {
    throw new Error(
      `ASSERT FAILED: expected exit code ${expected}, got ${result.exitCode}\nstdout: ${result.stdout}\nstderr: ${result.stderr}`,
    );
  }
}

export function assertDirExists(dir: string): void {
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) {
    throw new Error(`ASSERT FAILED: directory should exist but doesn't: ${dir}`);
  }
}

export function assertDirMissing(dir: string): void {
  if (fs.existsSync(dir)) {
    throw new Error(`ASSERT FAILED: directory should not exist but does: ${dir}`);
  }
}

export function assertFileExists(filePath: string): void {
  if (!fs.existsSync(filePath)) {
    throw new Error(`ASSERT FAILED: file should exist but doesn't: ${filePath}`);
  }
}

// ---------------------------------------------------------------------------
// Clean helper — resets the target directory to a blank state
// ---------------------------------------------------------------------------

/** Files/dirs generated by sbt that should be wiped before each test run. */
const GENERATED = [
  "supabase-tools.config.json",
  ".sbt",
  "supabase",
  "docs",
  ".gitignore",
];

/**
 * Remove all sbt-generated files from the target directory.
 * Leaves node_modules, package.json, etc. untouched.
 */
export function clean(targetDir: string): void {
  for (const name of GENERATED) {
    const fullPath = path.join(targetDir, name);
    fs.rmSync(fullPath, { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------------------
// Output helpers
// ---------------------------------------------------------------------------

const RED = "\x1b[31m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const CYAN = "\x1b[36m";
const BOLD = "\x1b[1m";
const RESET = "\x1b[0m";

export const log = {
  pass: (msg: string) => console.log(`${GREEN}  ✓${RESET} ${msg}`),
  fail: (msg: string) => console.error(`${RED}  ✗${RESET} ${msg}`),
  info: (msg: string) => console.log(`${CYAN}  →${RESET} ${msg}`),
  warn: (msg: string) => console.warn(`${YELLOW}  ⚠${RESET} ${msg}`),
  heading: (msg: string) => console.log(`\n${BOLD}${msg}${RESET}`),
  output: (text: string) => {
    const lines = text.trim().split("\n");
    for (const line of lines) console.log(`     ${line}`);
  },
};
